### ISSUE TITLE
VK SDK Request

### ISSUE THREAD

**Issue by dnikolaev** [marpies/vk-ane#1]
​Добрый день, @dreddik Роман.

Совместно с Марселем мы написали VK ANE https://github.com/marpies/vk-ane Текущая сборка включает последние версии iOS/Android SDK. ANE доступна для всех AS3/AIR разработчиков.

Если возможно, просим разместить ANE на странице https://new.vk.com/dev/SDK Также если необходимо можем перенести репозиторий в ваш аккаунт.

**Comment by RomanTruba** [comment]
👍 
Обсужу с коллегами

**Comment by dnikolaev** [comment]
@dreddik Роман, есть новости?

**Comment by dnikolaev** [comment]
@Dreddik Роман, добрый день. VK ANE уже проверен в продакшене. Найденные ошибки исправлены. Сейчас это самый актуальный и стабильный ANE для работы с VK.

Было бы здорово разместить его как официальный SDK для Adobe AIR платформы. 

Большинство игр в VK Каталоге сделаны на AS3/Flash технологии и разработчикам было бы удобно при портировании их на Android/iOS (Adobe AIR) использовать именно этот ANE.

**Comment by RomanTruba** [comment]
@dnikolaev здравствуйте! Я не принимаю таких решений. Скажите, вы связывались с Максимом Бабичевым?  Если да, то лучше продолжать контакт с ним

**Comment by dnikolaev** [comment]
@Dreddik Написал ему в VK. Дал ссылку на это обсуждение.
