### ISSUE TITLE
Invite Error -101

### ISSUE THREAD

**Issue by agnither** [marpies/vk-ane#10]
On Android I call invite request:
`VK.request
.setMethod("apps.sendRequest")
.setParameters({"user_id": userId,"text": text,"key": "invite","type": "invite"})
.send();`

But VK answers:
VKRequest::onError: null reason: null code: -101

Can I get any more helpful error message?

**Comment by agnither** [comment]
Actually, type="request" works just fine. But when I use "invite", even VK moderators can't see any success with this request.

**Comment by marpies** [comment]
Hi @agnithegreat,

The response you see is returned by the native VK SDK. I'm not sure why the request fails or what could be done to getter a better response from the SDK.

**Comment by agnither** [comment]
Finally, VK moderators approved the application and invites have started working properly.
