### ISSUE TITLE
iOS, OAuth flow, browser view openes after native app

### ISSUE THREAD

**Issue by fantomasst** [marpies/vk-ane#15]
Configurations are correct, CFBundleURLSchemes and LSApplicationQueriesSchemes are setted. 

Steps to reproduce:
1. open app
2. start auth flow -> native app opened
3. press "home button"
4. open app again -> app starts then browser view opens

**Comment by marpies** [comment]
Should be fixed in [v1.2.0](https://github.com/marpies/vk-ane/releases).
