### ISSUE TITLE
Myflashlab overrideAir does not work with VKontakte extension for Adobe AIR (iOS & Android) #11

### ISSUE THREAD

**Issue by denisgl7** [marpies/vk-ane#16]
I use myflashlab firebase
this library requires overrideAir ane (myflashlab)
the use of any override > 4.0.0 library does not allow this ane

**Comment by marpies** [comment]
Could you clarify what you mean by "override library does not allow this ane"? Do you get packaging or runtime errors? If so, can you share those errors?

**Comment by denisgl7** [comment]
Errors at runtime are not present
It just stops working. For example, registration stops working
```
VK.authorize( new <String>[], onAuthResult );
```
overrideAir 4.0.0 with which it works
http://dropmefiles.com/FAJTz
```
trace
[VK] Success auth
errorMessage: null
[VK] VK::sendRequestInternal()
[VK] Token update, callbacks 0
[VK] Request success
```
override 5.1.1 with which it does not work
http://dropmefiles.com/HL7sG
```
[VK] onInvoke standard args: 
```
back to my application the return does not go. Registration does not work

```
 <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
```

**Comment by denisgl7** [comment]
You can not fix it?

**Comment by marpies** [comment]
I did not have the chance to debug this fully yet. I will try this weekend, sorry for the delay.

**Comment by marpies** [comment]
I couldn't reproduce the issue on Android. I made some updates for iOS, please check the [1.2.0 release](https://github.com/marpies/vk-ane/releases).

**Comment by denisgl7** [comment]
It looks like it's working as it should!

**Comment by denisgl7** [comment]
Thank you a good man!

**Comment by marpies** [comment]
Great, thanks for testing!
