### ISSUE TITLE
Login doesn't work in ios 11

### ISSUE THREAD

**Issue by Klug76** [marpies/vk-ane#17]
We use the latest version 1.2.0, which ignores `InvokeEvent.INVOKE` and uses `application::openURL.`

Unfortunately in ios 11, the authorization process is stuck in the password entry dialog.

Application log:
``[-] ===app invoke 'vk5622047://authorize#access_token=**************&expires_in=0&user_id=**************,com.apple.SafariViewService,'
[-] ===
[-] VK::onAccessTokenUpdated | not logged in
[-] VK::onAuthResult | error: Something went wrong
[-] VK::onAuthResult | accessToken: null
[-] VK::onAuthResult | isLoggedIn: false``

**Comment by Klug76** [comment]
Quick & dirty fix is here: https://github.com/Klug76/vk-ane/blob/1f4e9f03f229fc726dd2813b2c10d92ccf730975/ios/VK/Utils/AIRVKSdkDelegate.m
based on https://github.com/AzureAD/azure-activedirectory-library-for-objc

**Comment by subdan** [comment]
I have the same issue. I'm unable to authorize. When I click Allow nothing happens.
