### ISSUE TITLE
[VK] Share error: Empty error message | Error code: -101

### ISSUE THREAD

**Issue by Ukiwuki** [marpies/vk-ane#8]
Hello, guys.

Trying to use VK.share functionality like described in demo app.
 VK.share
                    .setText( "Hello, sharing this fine link with you." )
                    .setAttachmentLink( "VK.com", "http://vk.com" )
                    .setCompleteCallback( onShareCompleted )
                    .setCancelCallback( onShareCancelled )
                    .setErrorCallback( onShareFailed )
                    .showDialog();

After that opens share dialog with provided text and link, but after pressing "Send" button I always get this error "[VK] Share error: Empty error message | Error code: -101".

What can I to debug/fix this?

**Comment by marpies** [comment]
Hi @Ukiwuki,

Indeed, the Android error message is not very helpful. The functionality seems to work fine for me, maybe you need to ask for `VKPermissions.WALL` when authorizing the user?

**Comment by Ukiwuki** [comment]
Thank you, VKPermissions.WALL solved it.
In initial test I've authorized app with VKPermissions.FRIENDS only. Later I changed permission to WALL. 

Though I had to call VK.logout() as app stayed logged in and didn't pickup new permission. After repeated authorization VK.share() worked properly.
